-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(PRODUCT.PRICE*OFFLINE_SALE.SALES_AMOUNT) as SALES
FROM PRODUCT
JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID=OFFLINE_SALE.PRODUCT_ID
WHERE SALES_AMOUNT in(
    SELECT SALES_AMOUNT
    GROUP BY PRODUCT_CODE)
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC,PRODUCT_CODE ASC

